//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tecan.VisionX.Sila2
{


    ///  <summary>
    /// This Feature provides control over the simulation behaviour of a SiLA Server.
    /// A SiLA Server can run in two modes:
    /// (a) Real Mode - with real activities, e.g. addressing or controlling real hardware, e.g. through serial/CANBus commands,
    /// writing to real databases, moving real objects etc.
    /// (b) Simulation Mode - where every command is only simulated and responses are just example returns.
    /// Note that certain commands and properties might not be affected by this feature if they
    /// do not interact with the real world.
    /// </summary>
    [Tecan.Sila2.SilaFeatureAttribute(false, "core")]
    [Tecan.Sila2.SilaIdentifierAttribute("SimulationController")]
    [Tecan.Sila2.SilaDisplayNameAttribute("Simulation Controller")]
    [Tecan.Sila2.SilaDescriptionAttribute(@"This Feature provides control over the simulation behaviour of a SiLA Server.

    A SiLA Server can run in two modes:
    (a) Real Mode - with real activities, e.g. addressing or controlling real hardware, e.g. through serial/CANBus commands,
        writing to real databases, moving real objects etc.
    (b) Simulation Mode - where every command is only simulated and responses are just example returns.

    Note that certain commands and properties might not be affected by this feature if they
    do not interact with the real world.")]
    public partial interface ISimulationController
    {
        
        ///  <summary>
        /// Indication whether SiLA Server is in Simulation Mode or not.
        /// </summary>
        [Tecan.Sila2.SilaDescriptionAttribute("Indication whether SiLA Server is in Simulation Mode or not.")]
        bool SimulationMode
        {
            get;
        }
        
        ///  <summary>
        /// Sets the SiLA Server to run in Simulation Mode, i.e. all following commands are executed in simulation mode.
        /// The Simulation Mode can only be entered, if all hardware operations have been safely terminated
        /// or are in a controlled, safe state.
        /// The simulation mode can be stopped by issuing the 'Start Real Mode' command.
        /// </summary>
        [Tecan.Sila2.SilaDisplayNameAttribute("Start Simulation Mode")]
        [Tecan.Sila2.SilaDescriptionAttribute(@"Sets the SiLA Server to run in Simulation Mode, i.e. all following commands are executed in simulation mode.

      The Simulation Mode can only be entered, if all hardware operations have been safely terminated
      or are in a controlled, safe state.

      The simulation mode can be stopped by issuing the 'Start Real Mode' command.")]
        [Tecan.Sila2.ThrowsAttribute(typeof(StartSimulationModeFailedException))]
        void StartSimulationMode();
        
        ///  <summary>
        /// Sets the SiLA Server to run in real mode, i.e. all following commands are executed with real-world
        /// interactions, like serial port/CAN communication, motor actions etc.
        /// If the server is in Simulation Mode it can be interrupted at any time. A re-initialization of
        /// the hardware might be required. The Real Mode can be stopped by issuing the 'Start Simulation Mode' command.
        /// </summary>
        [Tecan.Sila2.SilaDisplayNameAttribute("Start Real Mode")]
        [Tecan.Sila2.SilaDescriptionAttribute(@"Sets the SiLA Server to run in real mode, i.e. all following commands are executed with real-world
      interactions, like serial port/CAN communication, motor actions etc.

      If the server is in Simulation Mode it can be interrupted at any time. A re-initialization of
      the hardware might be required. The Real Mode can be stopped by issuing the 'Start Simulation Mode' command.")]
        [Tecan.Sila2.ThrowsAttribute(typeof(StartRealModeFailedException))]
        void StartRealMode();
    }
    
    ///  <summary>
    /// The server cannot change to Simulation Mode.
    /// This error can, e.g., be thrown, if a real-world process needs to be ended before switching to simulation
    /// mode.
    /// </summary>
    [Tecan.Sila2.SilaDisplayNameAttribute("The start of Simulation Mode failed.")]
    [Tecan.Sila2.SilaDescriptionAttribute("The server cannot change to Simulation Mode.\n      This error can, e.g., be throw" +
        "n, if a real-world process needs to be ended before switching to simulation\n    " +
        "  mode.")]
    public class StartSimulationModeFailedException : System.Exception
    {
        
        public StartSimulationModeFailedException(string message) : 
                base(message)
        {
        }
    }
    
    ///  <summary>
    /// The server cannot change to Real Mode.
    /// This error can, e.g., be thrown, if a device is not ready to change into Real Mode.
    /// </summary>
    [Tecan.Sila2.SilaDisplayNameAttribute("The start of Real Mode failed.")]
    [Tecan.Sila2.SilaDescriptionAttribute("The server cannot change to Real Mode.\n      This error can, e.g., be thrown, if " +
        "a device is not ready to change into Real Mode.")]
    public class StartRealModeFailedException : System.Exception
    {
        
        public StartRealModeFailedException(string message) : 
                base(message)
        {
        }
    }
}
