# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import SilaFluentController_pb2 as SilaFluentController__pb2


class SilaFluentControllerStub(object):
  """Feature: Fluent Service
  A service to send Commands to Fluent
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddLabware = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/AddLabware',
        request_serializer=SilaFluentController__pb2.AddLabware_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.AddLabware_Responses.FromString,
        )
    self.RemoveLabware = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/RemoveLabware',
        request_serializer=SilaFluentController__pb2.RemoveLabware_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.RemoveLabware_Responses.FromString,
        )
    self.SetLocation = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/SetLocation',
        request_serializer=SilaFluentController__pb2.SetLocation_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.SetLocation_Responses.FromString,
        )
    self.Subroutine = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/Subroutine',
        request_serializer=SilaFluentController__pb2.Subroutine_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.Subroutine_Responses.FromString,
        )
    self.TransferLabware = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/TransferLabware',
        request_serializer=SilaFluentController__pb2.TransferLabware_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.TransferLabware_Responses.FromString,
        )
    self.TransferLabwareBackToBase = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/TransferLabwareBackToBase',
        request_serializer=SilaFluentController__pb2.TransferLabwareBackToBase_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.TransferLabwareBackToBase_Responses.FromString,
        )
    self.GenericCommand = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/GenericCommand',
        request_serializer=SilaFluentController__pb2.GenericCommand_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.GenericCommand_Responses.FromString,
        )
    self.GetFingers = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/GetFingers',
        request_serializer=SilaFluentController__pb2.GetFingers_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.GetFingers_Responses.FromString,
        )
    self.DropFingers = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/DropFingers',
        request_serializer=SilaFluentController__pb2.DropFingers_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.DropFingers_Responses.FromString,
        )
    self.UserPrompt = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/UserPrompt',
        request_serializer=SilaFluentController__pb2.UserPrompt_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.UserPrompt_Responses.FromString,
        )
    self.GetTips = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/GetTips',
        request_serializer=SilaFluentController__pb2.GetTips_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.GetTips_Responses.FromString,
        )
    self.Aspirate = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/Aspirate',
        request_serializer=SilaFluentController__pb2.Aspirate_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.Aspirate_Responses.FromString,
        )
    self.DropTips = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/DropTips',
        request_serializer=SilaFluentController__pb2.DropTips_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.DropTips_Responses.FromString,
        )
    self.Dispense = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/Dispense',
        request_serializer=SilaFluentController__pb2.Dispense_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.Dispense_Responses.FromString,
        )
    self.StartFluent = channel.unary_unary(
        '/sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController/StartFluent',
        request_serializer=SilaFluentController__pb2.StartFluent_Parameters.SerializeToString,
        response_deserializer=SilaFluentController__pb2.StartFluent_Responses.FromString,
        )


class SilaFluentControllerServicer(object):
  """Feature: Fluent Service
  A service to send Commands to Fluent
  """

  def AddLabware(self, request, context):
    """AddLabware
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveLabware(self, request, context):
    """RemoveLabware
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetLocation(self, request, context):
    """SetLocation
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subroutine(self, request, context):
    """Subroutine
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferLabware(self, request, context):
    """TransferLabware
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferLabwareBackToBase(self, request, context):
    """TransferLabwareBackToBase
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GenericCommand(self, request, context):
    """GenericCommand
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFingers(self, request, context):
    """GetFingers
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropFingers(self, request, context):
    """DropFingers
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UserPrompt(self, request, context):
    """UserPrompt
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTips(self, request, context):
    """GetTips
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Aspirate(self, request, context):
    """Aspirate
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DropTips(self, request, context):
    """DropTips
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Dispense(self, request, context):
    """Dispense
    ...
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartFluent(self, request, context):
    """StartFluent
    Starts Fluent or connects to an instance already running
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SilaFluentControllerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddLabware': grpc.unary_unary_rpc_method_handler(
          servicer.AddLabware,
          request_deserializer=SilaFluentController__pb2.AddLabware_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.AddLabware_Responses.SerializeToString,
      ),
      'RemoveLabware': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveLabware,
          request_deserializer=SilaFluentController__pb2.RemoveLabware_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.RemoveLabware_Responses.SerializeToString,
      ),
      'SetLocation': grpc.unary_unary_rpc_method_handler(
          servicer.SetLocation,
          request_deserializer=SilaFluentController__pb2.SetLocation_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.SetLocation_Responses.SerializeToString,
      ),
      'Subroutine': grpc.unary_unary_rpc_method_handler(
          servicer.Subroutine,
          request_deserializer=SilaFluentController__pb2.Subroutine_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.Subroutine_Responses.SerializeToString,
      ),
      'TransferLabware': grpc.unary_unary_rpc_method_handler(
          servicer.TransferLabware,
          request_deserializer=SilaFluentController__pb2.TransferLabware_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.TransferLabware_Responses.SerializeToString,
      ),
      'TransferLabwareBackToBase': grpc.unary_unary_rpc_method_handler(
          servicer.TransferLabwareBackToBase,
          request_deserializer=SilaFluentController__pb2.TransferLabwareBackToBase_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.TransferLabwareBackToBase_Responses.SerializeToString,
      ),
      'GenericCommand': grpc.unary_unary_rpc_method_handler(
          servicer.GenericCommand,
          request_deserializer=SilaFluentController__pb2.GenericCommand_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.GenericCommand_Responses.SerializeToString,
      ),
      'GetFingers': grpc.unary_unary_rpc_method_handler(
          servicer.GetFingers,
          request_deserializer=SilaFluentController__pb2.GetFingers_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.GetFingers_Responses.SerializeToString,
      ),
      'DropFingers': grpc.unary_unary_rpc_method_handler(
          servicer.DropFingers,
          request_deserializer=SilaFluentController__pb2.DropFingers_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.DropFingers_Responses.SerializeToString,
      ),
      'UserPrompt': grpc.unary_unary_rpc_method_handler(
          servicer.UserPrompt,
          request_deserializer=SilaFluentController__pb2.UserPrompt_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.UserPrompt_Responses.SerializeToString,
      ),
      'GetTips': grpc.unary_unary_rpc_method_handler(
          servicer.GetTips,
          request_deserializer=SilaFluentController__pb2.GetTips_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.GetTips_Responses.SerializeToString,
      ),
      'Aspirate': grpc.unary_unary_rpc_method_handler(
          servicer.Aspirate,
          request_deserializer=SilaFluentController__pb2.Aspirate_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.Aspirate_Responses.SerializeToString,
      ),
      'DropTips': grpc.unary_unary_rpc_method_handler(
          servicer.DropTips,
          request_deserializer=SilaFluentController__pb2.DropTips_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.DropTips_Responses.SerializeToString,
      ),
      'Dispense': grpc.unary_unary_rpc_method_handler(
          servicer.Dispense,
          request_deserializer=SilaFluentController__pb2.Dispense_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.Dispense_Responses.SerializeToString,
      ),
      'StartFluent': grpc.unary_unary_rpc_method_handler(
          servicer.StartFluent,
          request_deserializer=SilaFluentController__pb2.StartFluent_Parameters.FromString,
          response_serializer=SilaFluentController__pb2.StartFluent_Responses.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sila2.contracts.remotefluent.silafluentcontroller.v1.SilaFluentController', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
